<?php
$pageTitle='Seating plans';
$totals=['all'=>count($allocations),'draft'=>0,'published'=>0,'superseded'=>0,'students'=>0,'exceptions'=>0];
foreach($allocations as $item){if(isset($totals[$item['status']]))$totals[$item['status']]++;$totals['students']+=(int)$item['assigned_count'];$totals['exceptions']+=(int)$item['unallocated_count'];}
?>
<div class="seating-page seating-enter">
  <section class="seating-command" aria-labelledby="seating-title"><div class="seating-command-copy"><div class="seating-lockup"><img src="<?= e(url('assets/images/gbu-emblem.png')) ?>" alt="" width="46" height="46"><div><strong>Gautam Buddha University</strong><span>Examination Cell</span></div></div><p class="seating-overline">Room-wise allocation control</p><h1 id="seating-title">Seating plans</h1><p>Generate, validate, and publish auditable room allocations for every examination session.</p></div><div class="seating-command-action"><div class="seat-map-symbol" aria-hidden="true"><i></i><i></i><i></i><i></i><i></i><i></i></div><span>Deterministic allocation engine</span><a href="<?= e(url('seating/generate')) ?>"><b class="ui-icon icon-spark" aria-hidden="true"></b>Generate seating<b aria-hidden="true">→</b></a></div></section>
  <?php if($success):?><div class="alert success" role="status"><?= e($success) ?></div><?php endif;?><?php if($error):?><div class="alert error" role="alert"><?= e($error) ?></div><?php endif;?>
  <section class="seating-kpis" aria-label="Seating summary"><div><span>Allocation versions</span><strong><?= number_format($totals['all']) ?></strong><small>Across all sessions</small></div><div><span>Published plans</span><strong><?= number_format($totals['published']) ?></strong><small>Approved for operations</small></div><div><span>Student placements</span><strong><?= number_format($totals['students']) ?></strong><small>Across saved versions</small></div><div class="<?= $totals['exceptions']?'attention':'' ?>"><span>Open exceptions</span><strong><?= number_format($totals['exceptions']) ?></strong><small><?= $totals['exceptions']?'Require manual resolution':'No pending exceptions' ?></small></div></section>
  <section class="seating-register-head"><div><strong>Allocation register</strong><span>Each regeneration creates a traceable version.</span></div><div class="seating-filters" aria-label="Filter allocations"><button class="active" type="button" data-seat-filter="all">All <span><?= $totals['all'] ?></span></button><button type="button" data-seat-filter="draft">Draft <span><?= $totals['draft'] ?></span></button><button type="button" data-seat-filter="published">Published <span><?= $totals['published'] ?></span></button><button type="button" data-seat-filter="superseded">Superseded <span><?= $totals['superseded'] ?></span></button></div></section>
  <?php if($allocations):?><section class="seating-register" aria-live="polite"><?php foreach($allocations as $allocation):?><article class="allocation-row-card" data-seat-status="<?= e($allocation['status']) ?>"><div class="allocation-date"><span><?= e(strtoupper(date('M',strtotime($allocation['exam_date'])))) ?></span><strong><?= e(date('d',strtotime($allocation['exam_date']))) ?></strong><small><?= e(date('Y',strtotime($allocation['exam_date']))) ?></small></div><div class="allocation-identity"><div><span class="seat-status <?= e($allocation['status']) ?>"><i aria-hidden="true"></i><?= e(ucfirst($allocation['status'])) ?></span><span>Version <?= (int)$allocation['version_no'] ?></span></div><h2><?= e($allocation['cycle_name']) ?></h2><p><b class="ui-icon icon-clock" aria-hidden="true"></b><?= e($allocation['shift_name']) ?></p></div><dl><div><dt>Students</dt><dd><?= number_format((int)$allocation['assigned_count']) ?></dd></div><div><dt>Rooms</dt><dd><?= number_format((int)$allocation['room_count']) ?></dd></div><div class="<?= (int)$allocation['unallocated_count']?'warn':'' ?>"><dt>Exceptions</dt><dd><?= number_format((int)$allocation['unallocated_count']) ?></dd></div></dl><a class="allocation-open" href="<?= e(url('seating/'.$allocation['id'])) ?>"><span>Open allocation</span><b aria-hidden="true">→</b></a></article><?php endforeach;?><div class="seating-filter-empty" hidden><strong>No allocations match this status</strong><span>Choose another filter to view saved versions.</span></div></section><?php else:?><section class="seating-empty"><div class="seat-map-symbol large" aria-hidden="true"><i></i><i></i><i></i><i></i><i></i><i></i></div><span>Allocation register</span><h2>No seating plans generated</h2><p>Schedule examination papers and calculate eligibility, then create your first room-wise allocation.</p><a href="<?= e(url('seating/generate')) ?>">Generate the first seating plan <b aria-hidden="true">→</b></a></section><?php endif;?>
</div>
<script>(()=>{const buttons=[...document.querySelectorAll('[data-seat-filter]')],rows=[...document.querySelectorAll('[data-seat-status]')],empty=document.querySelector('.seating-filter-empty');buttons.forEach(button=>button.addEventListener('click',()=>{buttons.forEach(item=>item.classList.toggle('active',item===button));const filter=button.dataset.seatFilter;let visible=0;rows.forEach((row,index)=>{const show=filter==='all'||row.dataset.seatStatus===filter;row.hidden=!show;if(show){visible++;row.style.setProperty('--seat-order',index);}});if(empty)empty.hidden=visible!==0;}));})();</script>
