<?php
declare(strict_types=1);
namespace App\Import;
use App\Exams\ExamService;use PDO;use RuntimeException;
final class DateSheetImportService
{
 public function __construct(private readonly PDO $pdo){}
 public function stage(int $cycleId,string $path,string $originalName,int $userId):int
 { $rows=(new TabularReader())->read($path,strtolower(pathinfo($originalName,PATHINFO_EXTENSION)));if(count($rows)<2)throw new RuntimeException('The file must contain a header and at least one paper.');$headers=array_map([$this,'key'],array_shift($rows));foreach(['exam_date','shift','course_code','course_name','programme_code','semester'] as $required)if(!in_array($required,$headers,true))throw new RuntimeException("Missing required column: {$required}.");
  $dates=[];$q=$this->pdo->prepare('SELECT exam_date FROM exam_calendar_dates WHERE cycle_id=:id AND is_exam_day=1');$q->execute(['id'=>$cycleId]);foreach($q->fetchAll(PDO::FETCH_COLUMN) as $d)$dates[$d]=true;$shifts=[];$q=$this->pdo->prepare('SELECT id,name,sequence_no FROM exam_shifts WHERE cycle_id=:id');$q->execute(['id'=>$cycleId]);foreach($q as $s){$shifts[strtolower(trim($s['name']))]=(int)$s['id'];$shifts[(string)$s['sequence_no']]=(int)$s['id'];}$programmes=[];foreach($this->pdo->query("SELECT id,code FROM programmes WHERE status IN ('active','unverified')") as $p)$programmes[strtoupper($p['code'])]=(int)$p['id'];
  $q=$this->pdo->prepare("INSERT INTO import_batches(import_type,original_filename,stored_filename,status,uploaded_by) VALUES('date_sheet',:original,:stored,'validating',:user)");$q->execute(['original'=>$originalName,'stored'=>basename($path),'user'=>$userId]);$batch=(int)$this->pdo->lastInsertId();$valid=0;$invalid=0;$insert=$this->pdo->prepare('INSERT INTO import_rows(import_batch_id,source_row_number,source_data,normalized_data,validation_status,validation_messages) VALUES(:batch,:row,:source,:normalized,:status,:messages)');
  foreach($rows as $index=>$values){$source=[];foreach($headers as $column=>$header)if($header!=='')$source[$header]=trim((string)($values[$column]??''));$messages=[];$date=$this->date($source['exam_date']??'');$shiftKey=strtolower($source['shift']??'');$programme=strtoupper($source['programme_code']??'');$semester=(int)($source['semester']??0);$course=strtoupper($source['course_code']??'');if(!$date||!isset($dates[$date]))$messages[]='Date is outside the cycle calendar.';if(!isset($shifts[$shiftKey]))$messages[]='Shift name or sequence was not found.';if(!isset($programmes[$programme]))$messages[]='Programme code was not found.';if($course===''||trim($source['course_name']??'')==='')$messages[]='Course code and name are required.';if($semester<1||$semester>12)$messages[]='Semester must be 1 to 12.';$category=$source['category']??'regular';if(!in_array($category,['regular','repeat','back_paper','special','pass_out','not_promoted'],true))$messages[]='Invalid category.';$data=['cycle_id'=>$cycleId,'shift_id'=>$shifts[$shiftKey]??null,'exam_date'=>$date,'course_code'=>$course,'course_name'=>trim($source['course_name']??''),'programme_id'=>$programmes[$programme]??null,'semester'=>$semester,'category'=>$category,'display_label'=>trim($source['display_label']??'')?:null];$status=$messages?'invalid':'valid';$messages?$invalid++:$valid++;$insert->execute(['batch'=>$batch,'row'=>$index+2,'source'=>json_encode($source),'normalized'=>json_encode($data),'status'=>$status,'messages'=>json_encode($messages)]);}
  $this->pdo->prepare("UPDATE import_batches SET status='review',total_rows=:total,valid_rows=:valid,invalid_rows=:invalid WHERE id=:id")->execute(['total'=>count($rows),'valid'=>$valid,'invalid'=>$invalid,'id'=>$batch]);return $batch; }
 public function commit(int $batchId,int $userId):int
 { $q=$this->pdo->prepare("SELECT * FROM import_batches WHERE id=:id AND import_type='date_sheet' AND status='review' FOR UPDATE");$q->execute(['id'=>$batchId]);if(!$q->fetch())throw new RuntimeException('Date-sheet import is not available for commit.');$q=$this->pdo->prepare("SELECT * FROM import_rows WHERE import_batch_id=:id AND validation_status='valid' ORDER BY source_row_number");$q->execute(['id'=>$batchId]);$count=0;$service=new ExamService($this->pdo);foreach($q as $row){$data=json_decode($row['normalized_data'],true,flags:JSON_THROW_ON_ERROR);$course=$this->pdo->prepare('SELECT id FROM courses WHERE code=:code');$course->execute(['code'=>$data['course_code']]);$courseId=(int)$course->fetchColumn();if(!$courseId){$this->pdo->prepare("INSERT INTO courses(code,name,status) VALUES(:code,:name,'active')")->execute(['code'=>$data['course_code'],'name'=>$data['course_name']]);$courseId=(int)$this->pdo->lastInsertId();}$this->pdo->prepare("INSERT INTO programme_courses(programme_id,course_id,semester,category) VALUES(:programme,:course,:semester,'core') ON DUPLICATE KEY UPDATE course_id=VALUES(course_id)")->execute(['programme'=>$data['programme_id'],'course'=>$courseId,'semester'=>$data['semester']]);unset($data['course_code'],$data['course_name']);$data['course_id']=$courseId;$exam=$service->schedule($data);$this->pdo->prepare('UPDATE import_rows SET committed_entity_id=:entity WHERE id=:id')->execute(['entity'=>$exam,'id'=>$row['id']]);$count++;}$this->pdo->prepare("UPDATE import_batches SET status='committed',committed_at=NOW() WHERE id=:id")->execute(['id'=>$batchId]);$this->pdo->prepare("INSERT INTO audit_logs(user_id,action,entity_type,entity_id,new_values) VALUES(:user,'date_sheet_import.committed','import_batch',:id,:data)")->execute(['user'=>$userId,'id'=>$batchId,'data'=>json_encode(['papers_created'=>$count])]);return $count; }
 private function key(string $header):string{$key=trim(preg_replace('/[^a-z0-9]+/','_',strtolower(trim($header)))??'','_');return ['date'=>'exam_date','shift_name'=>'shift','course'=>'course_code','paper_code'=>'course_code','paper_name'=>'course_name','programme'=>'programme_code','sem'=>'semester','label'=>'display_label'][$key]??$key;}
 private function date(string $value):?string{$value=trim($value);if(is_numeric($value)&&$value>1)return (new \DateTimeImmutable('1899-12-30'))->modify('+'.(int)$value.' days')->format('Y-m-d');foreach(['Y-m-d','d-m-Y','d/m/Y','d M Y','j M Y'] as $format){$d=\DateTimeImmutable::createFromFormat('!'.$format,$value);if($d&&$d->format($format)===$value)return $d->format('Y-m-d');}return null;}
}
