<?php
declare(strict_types=1);
define('BASE_PATH',dirname(__DIR__));require BASE_PATH.'/app/Support/helpers.php';spl_autoload_register(static function(string $class):void{$prefix='App\\';if(str_starts_with($class,$prefix))require BASE_PATH.'/app/'.str_replace('\\','/',substr($class,strlen($prefix))).'.php';});
use App\Exams\AutomaticScheduler;use App\Exams\SchedulePublicationService;use App\Exams\ScheduleReviewService;use App\Exams\SchedulingValidator;
$config=require BASE_PATH.'/config/database.php';$testDb='gbu_scheduler_'.bin2hex(random_bytes(4));if(!preg_match('/^gbu_scheduler_[a-f0-9]{8}$/',$testDb))throw new RuntimeException('Unsafe test database name.');
$server=new PDO("mysql:host={$config['host']};port={$config['port']};charset=utf8mb4",$config['username'],$config['password'],[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_EMULATE_PREPARES=>true]);
try{
 $server->exec(str_replace('gbu_exam_operations',$testDb,file_get_contents(BASE_PATH.'/database/schema.sql')));$server->exec(str_replace('gbu_exam_operations',$testDb,file_get_contents(BASE_PATH.'/database/seed.sql')));$pdo=new PDO("mysql:host={$config['host']};port={$config['port']};dbname={$testDb};charset=utf8mb4",$config['username'],$config['password'],[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]);
 $pdo->exec("INSERT INTO users(role_id,username,password_hash,name,status) SELECT id,'scheduler_test','test','Scheduler Test','active' FROM roles WHERE code='admin'");$user=(int)$pdo->lastInsertId();$pdo->exec("INSERT INTO schools(code,name,short_name,status) VALUES('TST','Test School','TST','active')");$school=(int)$pdo->lastInsertId();$pdo->prepare("INSERT INTO programmes(school_id,code,name,duration_semesters,status) VALUES(:school,'TST','Test Programme',8,'active')")->execute(['school'=>$school]);$programme=(int)$pdo->lastInsertId();
 foreach([['TS-101','Priority Paper',10],['TS-102','Later Paper',20]] as [$code,$name,$priority]){$pdo->prepare("INSERT INTO courses(code,name,status) VALUES(:code,:name,'active')")->execute(compact('code','name'));$course=(int)$pdo->lastInsertId();$pdo->prepare("INSERT INTO programme_courses(programme_id,course_id,semester,category,subject_priority) VALUES(:programme,:course,1,'core',:priority)")->execute(compact('programme','course','priority'));}
 assert((int)$pdo->query('SELECT COUNT(*) FROM students')->fetchColumn()===0);
 $pdo->prepare("INSERT INTO exam_cycles(name,academic_year,exam_type,start_date,end_date,default_duration_minutes,status,created_by) VALUES('Scheduler Test','2026-2027','end_sem','2026-12-01','2026-12-06',180,'draft',:user)")->execute(compact('user'));$cycle=(int)$pdo->lastInsertId();$pdo->prepare("INSERT INTO exam_shifts(cycle_id,name,start_time,end_time,duration_minutes,sequence_no) VALUES(:cycle,'Morning','09:30','12:30',180,1)")->execute(compact('cycle'));$shift=(int)$pdo->lastInsertId();$calendar=$pdo->prepare("INSERT INTO exam_calendar_dates(cycle_id,exam_date,is_exam_day,day_type,note) VALUES(:cycle,:date,:enabled,:type,:note)");foreach(['2026-12-01','2026-12-02','2026-12-03','2026-12-04','2026-12-05','2026-12-06'] as $date){$holiday=$date==='2026-12-02';$sunday=$date==='2026-12-06';$calendar->execute(['cycle'=>$cycle,'date'=>$date,'enabled'=>($holiday||$sunday)?0:1,'type'=>$holiday?'holiday':($sunday?'sunday':'exam_day'),'note'=>$holiday?'Test holiday':($sunday?'Sunday':null)]);}
 $scope=['cycle_id'=>$cycle,'school_id'=>$school,'programme_ids'=>[$programme],'semesters'=>[1],'minimum_gap_days'=>1,'maximum_papers_per_day'=>1,'avoid_consecutive_days'=>1,'use_subject_priority'=>1];
 $preview=(new SchedulingValidator($pdo))->validate($scope,$user,false);assert($preview['status']==='ready'&&$preview['run_id']===null);assert((int)$pdo->query('SELECT COUNT(*) FROM scheduling_runs')->fetchColumn()===0);

 $pdo->exec("INSERT INTO courses(code,name,status) VALUES('TS-LAB','Computer Programming Lab','active')");$labId=(int)$pdo->lastInsertId();
 $pdo->prepare("INSERT INTO programme_courses(programme_id,course_id,semester,category,subject_priority) VALUES(?,?,1,'core',1)")->execute([$programme,$labId]);
 $blockedLab=false;try{(new \App\Exams\ExamService($pdo))->schedule(['cycle_id'=>$cycle,'shift_id'=>$shift,'course_id'=>$labId,'programme_id'=>$programme,'semester'=>1,'exam_date'=>'2026-12-01','category'=>'regular']);}catch(RuntimeException $e){$blockedLab=str_contains($e->getMessage(),'Lab/practical');}assert($blockedLab);
 $validation=(new SchedulingValidator($pdo))->validate($scope,$user);assert($validation['status']==='ready');$generated=(new AutomaticScheduler($pdo))->generate($validation['run_id'],$user);assert($generated['scheduled']===2&&$generated['unscheduled']===0);assert((int)$pdo->query("SELECT COUNT(*) FROM examinations WHERE course_id={$labId}")->fetchColumn()===0);assert((int)$pdo->query('SELECT COUNT(*) FROM exam_eligibility')->fetchColumn()===0);
 $papers=$pdo->query("SELECT e.id,e.exam_date,c.code FROM examinations e JOIN courses c ON c.id=e.course_id ORDER BY e.exam_date")->fetchAll();assert($papers[0]['code']==='TS-101');assert($papers[0]['exam_date']==='2026-12-01'&&$papers[1]['exam_date']==='2026-12-03');assert(!in_array('2026-12-02',array_column($papers,'exam_date'),true));
 $review=new ScheduleReviewService($pdo);$review->setLock($validation['run_id'],(int)$papers[0]['id'],true,$user);$newRun=$review->prepareRegeneration($validation['run_id'],$user);$regenerated=(new AutomaticScheduler($pdo))->generate($newRun,$user);assert($regenerated['scheduled']===1);assert((int)$pdo->query("SELECT COUNT(*) FROM examinations WHERE id=".(int)$papers[0]['id']." AND is_locked=1")->fetchColumn()===1);
 $publication=new SchedulePublicationService($pdo);assert($publication->finalChecks($newRun)['blocked']===0);$publication->approve($newRun,$user);$publication->publish($newRun,$user);assert($pdo->query("SELECT status FROM scheduling_runs WHERE id={$newRun}")->fetchColumn()==='published');assert($pdo->query("SELECT status FROM exam_cycles WHERE id={$cycle}")->fetchColumn()==='published');assert((int)$pdo->query("SELECT COUNT(*) FROM examinations WHERE cycle_id={$cycle} AND status='published'")->fetchColumn()===2);
 echo "Automatic scheduling: PASS (priority, holiday, gap, lock, regeneration, approval, publication, lab exclusion)\n";
}finally{$server->exec("DROP DATABASE IF EXISTS `{$testDb}`");}
