<?php
declare(strict_types=1);
define('BASE_PATH',dirname(__DIR__));require BASE_PATH.'/app/Support/helpers.php';spl_autoload_register(static function(string $class):void{$prefix='App\\';if(str_starts_with($class,$prefix))require BASE_PATH.'/app/'.str_replace('\\','/',substr($class,strlen($prefix))).'.php';});
use App\Exams\ExamService;use App\Rooms\RoomSeatGenerator;use App\Seating\SeatingAllocator;
$config=require BASE_PATH.'/config/database.php';$testDb='gbu_exam_e2e_'.bin2hex(random_bytes(4));if(!preg_match('/^gbu_exam_e2e_[a-f0-9]{8}$/',$testDb))throw new RuntimeException('Unsafe test database name.');
$server=new PDO("mysql:host={$config['host']};port={$config['port']};charset=utf8mb4",$config['username'],$config['password'],[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_EMULATE_PREPARES=>true]);
try{
 $schema=str_replace('gbu_exam_operations',$testDb,file_get_contents(BASE_PATH.'/database/schema.sql'));$server->exec($schema);$seed=str_replace('gbu_exam_operations',$testDb,file_get_contents(BASE_PATH.'/database/seed.sql'));$server->exec($seed);$pdo=new PDO("mysql:host={$config['host']};port={$config['port']};dbname={$testDb};charset=utf8mb4",$config['username'],$config['password'],[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]);
 $pdo->exec("INSERT INTO users(role_id,username,password_hash,name,status) SELECT id,'e2e_admin','test','E2E Admin','active' FROM roles WHERE code='admin'");$user=(int)$pdo->lastInsertId();$programmeIds=[];foreach(['UCS','UCM'] as $code){$q=$pdo->prepare('SELECT id FROM programmes WHERE code=:code');$q->execute(['code'=>$code]);$programmeIds[$code]=(int)$q->fetchColumn();}
 $insert=$pdo->prepare("INSERT INTO students(programme_id,roll_no_original,academic_session,normalized_roll_no,programme_code_detected,student_sequence,name,branch,department_name,school_name,current_year_of_study,semester,section,parsing_status,status) VALUES(:programme,:roll,'2026-2027',:roll,:code,:sequence,:name,'Test Branch','Test Department','Test School',1,2,'A','verified','active')");$n=1;foreach($programmeIds as $code=>$programme)for($i=1;$i<=2;$i++){$roll='25'.$code.str_pad((string)$i,3,'0',STR_PAD_LEFT);$insert->execute(['programme'=>$programme,'roll'=>$roll,'code'=>$code,'sequence'=>(string)$i,'name'=>"Student {$n}"]);$n++;}
 $school=(int)$pdo->query("SELECT id FROM schools WHERE code='ICT'")->fetchColumn();$pdo->prepare("INSERT INTO faculty(school_id,employee_id,name,status) VALUES(:school,'FAC-E2E','Test Invigilator','active')")->execute(['school'=>$school]);$pdo->exec("INSERT INTO rooms(code,building,rows_count,columns_count,physical_capacity,usable_capacity,seat_order,status) VALUES('E2E-101','Test Block',1,3,3,3,'row_major','active')");$room=(int)$pdo->lastInsertId();assert((new RoomSeatGenerator($pdo))->regenerate($room,1,3,'row_major')===3);
 $exam=new ExamService($pdo);$cycle=$exam->createCycle(['name'=>'E2E Examination','academic_year'=>'2026-27','exam_type'=>'end_sem','start_date'=>'2026-09-01','end_date'=>'2026-09-02','duration'=>180,'shifts'=>[['name'=>'Morning','start'=>'09:30','end'=>'12:30','duration'=>180],['name'=>'Evening','start'=>'14:00','end'=>'17:00','duration'=>180]]],$user);$shift=(int)$pdo->query("SELECT id FROM exam_shifts WHERE cycle_id={$cycle} ORDER BY sequence_no LIMIT 1")->fetchColumn();
 foreach(['UCS'=>'CS-E2E','UCM'=>'ML-E2E'] as $code=>$courseCode){$pdo->prepare("INSERT INTO courses(code,name,status) VALUES(:code,:name,'active')")->execute(['code'=>$courseCode,'name'=>$courseCode.' Test Paper']);$course=(int)$pdo->lastInsertId();$pdo->prepare("INSERT INTO programme_courses(programme_id,course_id,semester,category) VALUES(:programme,:course,2,'core')")->execute(['programme'=>$programmeIds[$code],'course'=>$course]);$exam->schedule(['cycle_id'=>$cycle,'shift_id'=>$shift,'course_id'=>$course,'exam_date'=>'2026-09-01','category'=>'regular','programme_id'=>$programmeIds[$code],'semester'=>2,'display_label'=>$code.' Semester 2']);}
 $result=(new SeatingAllocator($pdo))->generate($cycle,'2026-09-01',$shift,[$room],$user,'e2e-seed');assert($result['assigned']===3&&$result['unallocated']===1);$validation=(new SeatingAllocator($pdo))->validate($result['allocation_id']);assert($validation['valid']===true);assert((int)$pdo->query("SELECT COUNT(*) FROM seating_unallocated WHERE allocation_id={$result['allocation_id']}")->fetchColumn()===1);
 $pdo->prepare("UPDATE seating_allocations SET status='published',published_at=NOW() WHERE id=:id")->execute(['id'=>$result['allocation_id']]);$pdo->prepare("INSERT INTO attendance(allocation_id,examination_id,room_id,student_id,status) SELECT allocation_id,examination_id,room_id,student_id,'unmarked' FROM seating_assignments WHERE allocation_id=:id")->execute(['id'=>$result['allocation_id']]);assert((int)$pdo->query("SELECT COUNT(*) FROM attendance WHERE allocation_id={$result['allocation_id']}")->fetchColumn()===3);
 echo "End-to-end: PASS (cycle, eligibility, 4 students, 3 seats, exception, validation, attendance)\n";
}finally{$server->exec("DROP DATABASE IF EXISTS `{$testDb}`");}
