<?php
declare(strict_types=1);
define('BASE_PATH',dirname(__DIR__));require BASE_PATH.'/app/Support/helpers.php';spl_autoload_register(static function(string $class):void{$prefix='App\\';if(str_starts_with($class,$prefix))require BASE_PATH.'/app/'.str_replace('\\','/',substr($class,strlen($prefix))).'.php';});
use App\Import\RoomImportService;
$ensure=static function(bool $condition,string $message):void{if(!$condition)throw new RuntimeException($message);};
$config=require BASE_PATH.'/config/database.php';$testDb='gbu_room_import_'.bin2hex(random_bytes(4));if(!preg_match('/^gbu_room_import_[a-f0-9]{8}$/',$testDb))throw new RuntimeException('Unsafe test database name.');
$server=new PDO("mysql:host={$config['host']};port={$config['port']};charset=utf8mb4",$config['username'],$config['password'],[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_EMULATE_PREPARES=>true]);$csv=tempnam(sys_get_temp_dir(),'gbu_rooms_');
try{
 $server->exec(str_replace('gbu_exam_operations',$testDb,file_get_contents(BASE_PATH.'/database/schema.sql')));$server->exec(str_replace('gbu_exam_operations',$testDb,file_get_contents(BASE_PATH.'/database/seed.sql')));$pdo=new PDO("mysql:host={$config['host']};port={$config['port']};dbname={$testDb};charset=utf8mb4",$config['username'],$config['password'],[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]);
 $pdo->exec("INSERT INTO users(role_id,username,password_hash,name,status) SELECT id,'room_test','test','Room Test','active' FROM roles WHERE code='admin'");$user=(int)$pdo->lastInsertId();
 file_put_contents($csv,"Room Code,Building,Floor,Rows,Columns,Seat Order,Disabled Seat Numbers,Priority,Status,Notes\nICT-T01,ICT Block,First Floor,3,4,column_major,R02-C02 | R03-C04,10,active,Test room\nICT-T02,ICT Block,,2,2,,,,,\nICT-BAD,ICT Block,,2,2,row_major,R03-C01,20,active,Invalid blocked coordinate\n");
 $service=new RoomImportService($pdo);$batch=$service->stage($csv,'rooms.csv',$user);$summary=$pdo->query("SELECT total_rows,valid_rows,invalid_rows FROM import_batches WHERE id={$batch}")->fetch();$ensure((int)$summary['total_rows']===3&&(int)$summary['valid_rows']===2&&(int)$summary['invalid_rows']===1,'Unexpected validation totals.');
 $pdo->beginTransaction();$created=$service->commit($batch,$user);$pdo->commit();$ensure($created===2,'Expected two imported rooms.');$room=$pdo->query("SELECT * FROM rooms WHERE code='ICT-T01'")->fetch();$ensure((int)$room['physical_capacity']===12&&(int)$room['usable_capacity']===10,'Capacity calculation failed.');$blocked=(int)$pdo->query("SELECT COUNT(*) FROM room_seats WHERE room_id=".(int)$room['id']." AND is_blocked=1")->fetchColumn();$ensure($blocked===2,'Disabled-seat count failed.');$labels=$pdo->query("SELECT GROUP_CONCAT(seat_label ORDER BY seat_label) FROM room_seats WHERE room_id=".(int)$room['id']." AND is_blocked=1")->fetchColumn();$ensure($labels==='R02-C02,R03-C04','Disabled-seat labels failed.');$defaults=$pdo->query("SELECT seat_order,priority,status FROM rooms WHERE code='ICT-T02'")->fetch();$ensure($defaults['seat_order']==='column_major'&&(int)$defaults['priority']===100&&$defaults['status']==='active','Optional defaults failed.');
 $demo=BASE_PATH.'/storage/demo-data/large-multi-branch/gbu_rooms_proposed_demo.csv';$demoBatch=$service->stage($demo,'gbu_rooms_proposed_demo.csv',$user);$demoSummary=$pdo->query("SELECT total_rows,valid_rows,invalid_rows FROM import_batches WHERE id={$demoBatch}")->fetch();$ensure((int)$demoSummary['total_rows']===20&&(int)$demoSummary['valid_rows']===20&&(int)$demoSummary['invalid_rows']===0,'Proposed GBU room CSV did not fully validate.');
 echo "Room import: PASS (preview validation, commit, geometry, disabled seats)\n";
}finally{if(is_file($csv))unlink($csv);$server->exec("DROP DATABASE IF EXISTS `{$testDb}`");}
