<?php
declare(strict_types=1);
define('BASE_PATH',dirname(__DIR__));require BASE_PATH.'/app/Support/helpers.php';spl_autoload_register(static function(string $class):void{$prefix='App\\';if(str_starts_with($class,$prefix))require BASE_PATH.'/app/'.str_replace('\\','/',substr($class,strlen($prefix))).'.php';});
use App\Exams\AutomaticScheduler;use App\Exams\SchedulePublicationService;use App\Exams\ScheduleReviewService;use App\Exams\SchedulingValidator;
$config=require BASE_PATH.'/config/database.php';$testDb='gbu_soict_'.bin2hex(random_bytes(4));if(!preg_match('/^gbu_soict_[a-f0-9]{8}$/',$testDb))throw new RuntimeException('Unsafe test database name.');
$server=new PDO("mysql:host={$config['host']};port={$config['port']};charset=utf8mb4",$config['username'],$config['password'],[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_EMULATE_PREPARES=>true]);
try{
 $server->exec(str_replace('gbu_exam_operations',$testDb,file_get_contents(BASE_PATH.'/database/schema.sql')));$server->exec(str_replace('gbu_exam_operations',$testDb,file_get_contents(BASE_PATH.'/database/seed.sql')));$pdo=new PDO("mysql:host={$config['host']};port={$config['port']};dbname={$testDb};charset=utf8mb4",$config['username'],$config['password'],[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]);
 $pdo->exec("INSERT INTO users(role_id,username,password_hash,name,status) SELECT id,'scheduler_test','test','Scheduler Test','active' FROM roles WHERE code='admin'");$user=(int)$pdo->lastInsertId();$pdo->exec("INSERT INTO schools(code,name,short_name,status) VALUES('TST','Test School','TST','active')");$school=(int)$pdo->lastInsertId();$pdo->prepare("INSERT INTO programmes(school_id,code,name,duration_semesters,status) VALUES(:school,'TST','Test Programme',8,'active')")->execute(['school'=>$school]);$programme=(int)$pdo->lastInsertId();
 foreach([['TS-101','Priority Paper',10],['TS-102','Later Paper',20]] as [$code,$name,$priority]){$pdo->prepare("INSERT INTO courses(code,name,status) VALUES(:code,:name,'active')")->execute(compact('code','name'));$course=(int)$pdo->lastInsertId();$pdo->prepare("INSERT INTO programme_courses(programme_id,course_id,semester,category,subject_priority) VALUES(:programme,:course,1,'core',:priority)")->execute(compact('programme','course','priority'));}
 $pdo->prepare("INSERT INTO students(programme_id,roll_no_original,academic_session,normalized_roll_no,name,branch,department_name,school_name,current_year_of_study,semester,status) VALUES(:programme,'260TST001','2026-2027','260TST001','Test Student','Test','Test','Test',1,1,'active')")->execute(compact('programme'));
 $pdo->prepare("INSERT INTO exam_cycles(name,academic_year,exam_type,start_date,end_date,default_duration_minutes,status,created_by) VALUES('Scheduler Test','2026-2027','end_sem','2026-12-01','2026-12-06',180,'draft',:user)")->execute(compact('user'));$cycle=(int)$pdo->lastInsertId();$pdo->prepare("INSERT INTO exam_shifts(cycle_id,name,start_time,end_time,duration_minutes,sequence_no) VALUES(:cycle,'Morning','09:30','12:30',180,1)")->execute(compact('cycle'));$shift=(int)$pdo->lastInsertId();$calendar=$pdo->prepare("INSERT INTO exam_calendar_dates(cycle_id,exam_date,is_exam_day,day_type,note) VALUES(:cycle,:date,:enabled,:type,:note)");foreach(['2026-12-01','2026-12-02','2026-12-03','2026-12-04','2026-12-05','2026-12-06'] as $date){$holiday=$date==='2026-12-02';$sunday=$date==='2026-12-06';$calendar->execute(['cycle'=>$cycle,'date'=>$date,'enabled'=>($holiday||$sunday)?0:1,'type'=>$holiday?'holiday':($sunday?'sunday':'exam_day'),'note'=>$holiday?'Test holiday':($sunday?'Sunday':null)]);}

 $pdo->prepare("INSERT INTO programmes(school_id,code,name,duration_semesters,status) VALUES(?,'TSB','Second Branch',8,'active')")->execute([$school]);$second=(int)$pdo->lastInsertId();
 $pdo->prepare("INSERT INTO programme_courses(programme_id,course_id,semester,category,subject_priority) SELECT ?,course_id,semester,category,subject_priority FROM programme_courses WHERE programme_id=?")->execute([$second,$programme]);
 $validation=(new SchedulingValidator($pdo))->validate(['cycle_id'=>$cycle,'school_id'=>$school,'programme_ids'=>[$programme,$second],'semesters'=>[1],'minimum_gap_days'=>1,'maximum_papers_per_day'=>1,'avoid_consecutive_days'=>1,'use_subject_priority'=>1],$user);assert($validation['status']==='ready');$generated=(new AutomaticScheduler($pdo))->generate($validation['run_id'],$user);assert($generated['scheduled']===4&&$generated['unscheduled']===0);
 $papers=$pdo->query("SELECT e.id,e.exam_date,c.code FROM examinations e JOIN courses c ON c.id=e.course_id ORDER BY e.exam_date")->fetchAll();assert($papers[0]['code']==='TS-101');assert($papers[0]['exam_date']==='2026-12-01'&&$papers[1]['exam_date']==='2026-12-03');assert(!in_array('2026-12-02',array_column($papers,'exam_date'),true));

 assert((int)$pdo->query("SELECT COUNT(*) FROM examination_cohorts WHERE examination_id=".(int)$papers[0]['id'])->fetchColumn()===2);
 $repeat=(new SchedulingValidator($pdo))->validate(['cycle_id'=>$cycle,'school_id'=>$school,'programme_ids'=>[$programme,$second],'semesters'=>[1],'minimum_gap_days'=>1,'maximum_papers_per_day'=>1],$user);
 $again=(new AutomaticScheduler($pdo))->generate($repeat['run_id'],$user);assert($again['scheduled']===0);
 assert((int)$pdo->query("SELECT COUNT(*) FROM examinations WHERE cycle_id={$cycle}")->fetchColumn()===2);
 $review=new ScheduleReviewService($pdo);$review->setLock($validation['run_id'],(int)$papers[0]['id'],true,$user);$newRun=$review->prepareRegeneration($validation['run_id'],$user);$regenerated=(new AutomaticScheduler($pdo))->generate($newRun,$user);assert($regenerated['scheduled']===2);assert((int)$pdo->query("SELECT COUNT(*) FROM examinations WHERE id=".(int)$papers[0]['id']." AND is_locked=1")->fetchColumn()===1);
 $publication=new SchedulePublicationService($pdo);assert($publication->finalChecks($newRun)['blocked']===0);$publication->approve($newRun,$user);$publication->publish($newRun,$user);assert($pdo->query("SELECT status FROM scheduling_runs WHERE id={$newRun}")->fetchColumn()==='published');assert($pdo->query("SELECT status FROM exam_cycles WHERE id={$cycle}")->fetchColumn()==='published');assert((int)$pdo->query("SELECT COUNT(*) FROM examinations WHERE cycle_id={$cycle} AND status='published'")->fetchColumn()===2);

 $examService=new \App\Exams\ExamService($pdo);
 $twoShiftCycle=$examService->createCycle(['name'=>'Two shifts','academic_year'=>'2026-2027','exam_type'=>'end_sem','start_date'=>'2026-12-07','end_date'=>'2026-12-07','duration'=>180,'shifts'=>[['name'=>'Morning','start'=>'09:30','end'=>'12:30','duration'=>180],['name'=>'Afternoon','start'=>'14:00','end'=>'17:00','duration'=>180]]],$user);
 $zero=(new SchedulingValidator($pdo))->validate(['cycle_id'=>$twoShiftCycle,'school_id'=>$school,'programme_ids'=>[$programme,$second],'semesters'=>[1],'minimum_gap_days'=>0,'maximum_papers_per_day'=>2],$user);assert($zero['status']==='ready');
 $zeroResult=(new AutomaticScheduler($pdo))->generate($zero['run_id'],$user);assert($zeroResult['scheduled']===4&&$zeroResult['unscheduled']===0);
 assert((int)$pdo->query("SELECT COUNT(DISTINCT shift_id) FROM examinations WHERE cycle_id={$twoShiftCycle}")->fetchColumn()===2);
 foreach([[$programme,'BR-A-201','Branch A subject'],[$second,'BR-B-201','Branch B subject']] as [$branch,$code,$name]){$pdo->prepare("INSERT INTO courses(code,name,status) VALUES(?,?,'active')")->execute([$code,$name]);$course=(int)$pdo->lastInsertId();$pdo->prepare("INSERT INTO programme_courses(programme_id,course_id,semester,category,subject_priority) VALUES(?,?,2,'core',10)")->execute([$branch,$course]);}
 $parallelCycle=$examService->createCycle(['name'=>'Parallel branches','academic_year'=>'2026-2027','exam_type'=>'end_sem','start_date'=>'2026-12-10','end_date'=>'2026-12-10','duration'=>180,'shifts'=>[['name'=>'Morning','start'=>'09:30','end'=>'12:30','duration'=>180]]],$user);
 $parallel=(new SchedulingValidator($pdo))->validate(['cycle_id'=>$parallelCycle,'school_id'=>$school,'programme_ids'=>[$programme,$second],'semesters'=>[2],'minimum_gap_days'=>1,'maximum_papers_per_day'=>1],$user);assert($parallel['status']==='ready');
 $parallelResult=(new AutomaticScheduler($pdo))->generate($parallel['run_id'],$user);assert($parallelResult['scheduled']===2&&$parallelResult['unscheduled']===0);
 assert((int)$pdo->query("SELECT COUNT(*) FROM examinations WHERE cycle_id={$parallelCycle} AND exam_date='2026-12-10'")->fetchColumn()===2);
 assert((int)$pdo->query("SELECT COUNT(DISTINCT CONCAT(exam_date,'-',shift_id)) FROM examinations WHERE cycle_id={$parallelCycle}")->fetchColumn()===1);
 $shortCycle=$examService->createCycle(['name'=>'Short shift','academic_year'=>'2026-2027','exam_type'=>'end_sem','start_date'=>'2026-12-08','end_date'=>'2026-12-09','duration'=>90,'shifts'=>[['name'=>'Short','start'=>'09:30','end'=>'11:00','duration'=>90]]],$user);
 $short=(new SchedulingValidator($pdo))->validate(['cycle_id'=>$shortCycle,'school_id'=>$school,'programme_ids'=>[$programme,$second],'semesters'=>[1],'minimum_gap_days'=>0,'maximum_papers_per_day'=>1],$user);assert($short['status']==='ready');
 $shortResult=(new AutomaticScheduler($pdo))->generate($short['run_id'],$user);assert($shortResult['scheduled']===0&&$shortResult['unscheduled']===4);
 echo "SOICT: PASS (separate branch rows, parallel different subjects, shared subjects, no duplicate regeneration, locks, publication, zero-gap multiple shifts, duration constraints)\n";
}finally{$server->exec("DROP DATABASE IF EXISTS `{$testDb}`");}
