<?php $pageTitle='Batches'; ?>
<div class="gov-page gov-enter">
  <section class="gov-hero"><div><div class="gov-brand"><img src="<?= e(url('assets/images/gbu-emblem.png')) ?>" alt="" width="44" height="44"><span>Gautam Buddha University<br><b>Academic master data</b></span></div><h1>Programme batches</h1><p>Maintain admission cohorts independently for every programme and academic session.</p></div><div class="gov-hero-stat"><i class="ti ti-users-group" aria-hidden="true"></i><strong><?= count($batches) ?></strong><small>filtered batches</small></div></section>
  <?php if($success):?><div class="alert success" role="status"><?= e($success) ?></div><?php endif;?><?php if($error):?><div class="alert error" role="alert"><?= e($error) ?></div><?php endif;?>
  <div class="master-workspace programme-workspace">
    <form class="master-create" method="post" action="<?= e(url('masters/batches')) ?>"><?= csrf_field() ?><header><i class="ti ti-calendar-plus" aria-hidden="true"></i><div><h2>Create programme batch</h2><p>The end year is calculated from programme duration.</p></div></header>
      <label>Programme<select name="programme_id" required><option value="">Select programme</option><?php foreach($programmes as $programme):?><option value="<?= (int)$programme['id'] ?>"><?= e($programme['code'].' - '.$programme['name'].' ('.(int)$programme['duration_semesters'].' semesters)') ?></option><?php endforeach;?></select></label>
      <label>Admission year<input type="number" name="start_year" min="2000" max="2100" value="<?= date('Y') ?>" required><small>Example: 2023 produces UCS 2023-2027 for an eight-semester programme.</small></label>
      <label>Status<select name="status"><option value="active">Active</option><option value="completed">Completed</option><option value="inactive">Inactive</option></select></label>
      <button><span>Save batch</span><b aria-hidden="true">→</b></button>
    </form>
    <section class="master-register"><header><div><h2>Batch register</h2><p>Student and examination records remain separated by admission cohort.</p></div></header>
      <form class="filter-bar" method="get"><label>Programme<select name="programme_id"><option value="">All programmes</option><?php foreach($programmes as $programme):?><option value="<?= (int)$programme['id'] ?>" <?= $programmeId===(int)$programme['id']?'selected':'' ?>><?= e($programme['code'].' - '.$programme['name']) ?></option><?php endforeach;?></select></label><label>Status<select name="status"><option value="">All statuses</option><?php foreach(['active','completed','inactive'] as $value):?><option value="<?= $value ?>" <?= $statusFilter===$value?'selected':'' ?>><?= e(ucfirst($value)) ?></option><?php endforeach;?></select></label><button class="secondary-button">Apply filters</button></form>
      <?php if($batches):?><div class="programme-list"><?php foreach($batches as $batch):?><article><div class="programme-code"><span><?= e($batch['programme_code']) ?></span><small><?= e((string)$batch['start_year']) ?></small></div><div><h3><?= e($batch['label']) ?></h3><p><?= e($batch['programme_name']) ?></p></div><div class="programme-level"><strong><?= (int)$batch['student_count'] ?> students</strong><span><?= (int)$batch['cycle_count'] ?> examination cycles</span></div><span class="gov-status <?= e($batch['status']) ?>"><?= e(ucfirst($batch['status'])) ?></span></article><?php endforeach;?></div><?php else:?><div class="gov-empty"><i class="ti ti-users-group" aria-hidden="true"></i><h2>No batches found</h2><p>Create a batch or change the filters.</p></div><?php endif;?>
    </section>
  </div>
  <section class="panel table-panel"><div class="table-toolbar"><strong>Programme duration management</strong><span>Duration controls calculated batch end years.</span></div><div class="table-scroll"><table><thead><tr><th>Programme</th><th>Level</th><th>Duration</th><th></th></tr></thead><tbody><?php foreach($programmes as $programme):?><tr><td><strong><?= e($programme['code']) ?></strong><small class="cell-note"><?= e($programme['name']) ?></small></td><td><?= e(ucfirst($programme['lateral_entry']?'lateral entry':($programme['legacy']?'legacy':'regular'))) ?></td><td><form method="post" action="<?= e(url('masters/programmes/'.$programme['id'].'/duration')) ?>" class="filter-bar"><?= csrf_field() ?><label><span class="sr-only">Duration semesters</span><input type="number" name="duration_semesters" min="1" max="20" value="<?= (int)$programme['duration_semesters'] ?>" required></label><span>semesters</span><button class="secondary-button">Update duration</button></form></td><td><?= (int)ceil((int)$programme['duration_semesters']/2) ?> academic years</td></tr><?php endforeach;?></tbody></table></div></section>
</div>
