<?php $editing=is_array($room);$pageTitle=$editing?'Edit room':'Add room';$values=array_merge($room??[],$old);$blockedValue=$old['blocked']??$blocked; ?>
<section class="page-heading"><div><p class="eyebrow">Room management</p><h1><?= $editing?'Edit room and seat map':'Create room and seat map' ?></h1><p>Define the geometry, then click individual seats to exclude them from examination allocation.</p></div><a class="secondary-button" href="<?= e(url('rooms')) ?>">Back to rooms</a></section>
<form id="room-form" class="record-form room-builder" method="post" action="<?= e($editing?url('rooms/'.$room['id']):url('rooms')) ?>"><?= csrf_field() ?>
  <section class="panel form-section"><div class="form-section-heading"><p class="eyebrow">Location</p><h2>Room identity</h2></div><div class="form-grid two"><label>Room code<input name="code" value="<?= e($values['code']??'') ?>" placeholder="ICT-101" required><?php if(isset($errors['code'])):?><b><?= e($errors['code']) ?></b><?php endif;?></label><label>Building<input name="building" value="<?= e($values['building']??'') ?>" placeholder="ICT Block" required></label><label>Floor<input name="floor" value="<?= e($values['floor']??'') ?>" placeholder="First floor"></label><label>Priority<input type="number" name="priority" min="1" value="<?= e((string)($values['priority']??100)) ?>"><small>Lower numbers are allocated first.</small></label></div></section>
  <section class="panel form-section room-geometry"><div class="form-section-heading"><p class="eyebrow">Interactive geometry</p><h2>Build the physical seat map</h2><p>Change rows or columns to regenerate the preview. Click a seat to enable or disable it.</p></div><div class="form-grid three"><label>Rows<input id="room-rows" type="number" name="rows_count" min="1" max="100" value="<?= e((string)($values['rows_count']??5)) ?>" required><?php if(isset($errors['rows_count'])):?><b><?= e($errors['rows_count']) ?></b><?php endif;?></label><label>Columns<input id="room-columns" type="number" name="columns_count" min="1" max="100" value="<?= e((string)($values['columns_count']??8)) ?>" required><?php if(isset($errors['columns_count'])):?><b><?= e($errors['columns_count']) ?></b><?php endif;?></label><label>Seat fill order<select name="seat_order"><option value="column_major" <?= ($values['seat_order']??'column_major')==='column_major'?'selected':'' ?>>Column major</option><option value="row_major" <?= ($values['seat_order']??'')==='row_major'?'selected':'' ?>>Row major</option></select></label></div>
    <input id="blocked-seats" type="hidden" name="blocked" value="<?= e($blockedValue) ?>">
    <div class="seat-editor-toolbar"><div class="seat-editor-legend"><span><i class="available"></i>Available</span><span><i class="disabled"></i>Disabled</span></div><div class="seat-editor-counts"><span>Physical <b id="physical-count">0</b></span><span>Usable <b id="usable-count">0</b></span><span>Disabled <b id="disabled-count">0</b></span><button id="enable-all-seats" type="button">Enable all</button></div></div>
    <div class="seat-editor-stage"><div class="seat-editor-board">WHITE BOARD</div><div id="seat-editor-grid" class="seat-editor-grid" role="group" aria-label="Room seats"></div><p class="seat-editor-help">Select a seat to disable it. Disabled seats will never be used by the seating allocator.</p></div>
    <details class="coordinate-editor"><summary>View or enter disabled seat numbers</summary><label>Disabled seats<textarea id="blocked-seats-text" rows="3" placeholder="R02-C04 | R03-C04"><?= e($blockedValue) ?></textarea><small>Use seat numbers such as R02-C04, separated with a vertical bar, comma, or semicolon.</small></label></details>
  </section>
  <section class="panel form-section"><div class="form-section-heading"><p class="eyebrow">Availability</p><h2>Operational status</h2></div><div class="form-grid two"><label>Status<select name="status"><option value="active" <?= ($values['status']??'active')==='active'?'selected':'' ?>>Active</option><option value="inactive" <?= ($values['status']??'')==='inactive'?'selected':'' ?>>Inactive</option><option value="maintenance" <?= ($values['status']??'')==='maintenance'?'selected':'' ?>>Maintenance</option></select></label><label>Notes<input name="notes" value="<?= e($values['notes']??'') ?>" placeholder="Accessibility or examination notes"></label></div></section>
  <div class="form-actions"><a class="text-button" href="<?= e(url('rooms')) ?>">Cancel</a><button class="primary-button"><?= $editing?'Save room layout':'Create room' ?></button></div>
</form>
<script>(()=>{const rows=document.getElementById('room-rows'),columns=document.getElementById('room-columns'),grid=document.getElementById('seat-editor-grid'),hidden=document.getElementById('blocked-seats'),text=document.getElementById('blocked-seats-text'),physical=document.getElementById('physical-count'),usable=document.getElementById('usable-count'),disabled=document.getElementById('disabled-count'),enableAll=document.getElementById('enable-all-seats');let blocked=new Set();const key=(r,c)=>`${r}-${c}`,label=(r,c)=>`R${String(r).padStart(2,'0')}-C${String(c).padStart(2,'0')}`;const parse=value=>{const set=new Set();String(value||'').split(/[|;,]+/).map(item=>item.trim().toUpperCase()).filter(Boolean).forEach(item=>{const match=item.match(/^(?:R)?0*(\d+)(?:\s*[-:]\s*C?0*(\d+))$/);if(match)set.add(key(Number(match[1]),Number(match[2])));});return set;};const sync=()=>{const maxRow=Number(rows.value)||0,maxColumn=Number(columns.value)||0;blocked=new Set([...blocked].filter(item=>{const [r,c]=item.split('-').map(Number);return r>=1&&r<=maxRow&&c>=1&&c<=maxColumn;}));const ordered=[...blocked].sort((a,b)=>{const [ar,ac]=a.split('-').map(Number),[br,bc]=b.split('-').map(Number);return ar-br||ac-bc;});hidden.value=ordered.join(',');text.value=ordered.map(item=>{const [r,c]=item.split('-');return label(r,c);}).join(' | ');physical.textContent=(maxRow*maxColumn).toLocaleString();disabled.textContent=ordered.length.toLocaleString();usable.textContent=Math.max(0,maxRow*maxColumn-ordered.length).toLocaleString();};const render=()=>{const maxRow=Math.min(100,Math.max(1,Number(rows.value)||1)),maxColumn=Math.min(100,Math.max(1,Number(columns.value)||1));rows.value=maxRow;columns.value=maxColumn;grid.style.setProperty('--seat-columns',maxColumn);const fragment=document.createDocumentFragment();for(let r=1;r<=maxRow;r++)for(let c=1;c<=maxColumn;c++){const coordinate=key(r,c),button=document.createElement('button');button.type='button';button.className='seat-editor-seat';button.dataset.coordinate=coordinate;button.textContent=label(r,c);button.setAttribute('aria-pressed',String(blocked.has(coordinate)));button.setAttribute('aria-label',`${label(r,c)} ${blocked.has(coordinate)?'disabled':'available'}`);button.addEventListener('click',()=>{blocked.has(coordinate)?blocked.delete(coordinate):blocked.add(coordinate);button.setAttribute('aria-pressed',String(blocked.has(coordinate)));button.setAttribute('aria-label',`${label(r,c)} ${blocked.has(coordinate)?'disabled':'available'}`);sync();});fragment.append(button);}grid.replaceChildren(fragment);sync();};blocked=parse(hidden.value);rows.addEventListener('change',render);columns.addEventListener('change',render);text.addEventListener('change',()=>{blocked=parse(text.value);render();});enableAll.addEventListener('click',()=>{blocked.clear();render();});render();})();</script>
