<?php $editing=is_array($student);$pageTitle=$editing?'Edit student':'Add student';$values=array_merge($student??[],$old);$field=function(string $name)use($errors):string{return isset($errors[$name])?'has-error':'';}; ?>
<section class="page-heading"><div><p class="eyebrow">Student management</p><h1><?= $editing?'Edit student record':'Add a student' ?></h1><p>Capture the complete university identity, contact, and current academic placement.</p></div><a class="secondary-button" href="<?= e(url('students')) ?>">Back to students</a></section>
<form class="record-form" method="post" action="<?= e($editing?url('students/'.$student['id']):url('students')) ?>"><?= csrf_field() ?>
<section class="panel form-section"><div class="form-section-heading"><p class="eyebrow">Identity</p><h2>Official student details</h2></div><div class="form-grid two">
<label class="<?= $field('roll_no_original') ?>">Enrollment / Roll Number<input name="roll_no_original" value="<?= e($values['roll_no_original']??'') ?>" placeholder="245UCS005" required><?php if(isset($errors['roll_no_original'])):?><b><?= e($errors['roll_no_original']) ?></b><?php endif;?></label>
<label>Enrollment Number <small>Optional when different from the roll number</small><input name="enrollment_number" value="<?= e($values['enrollment_number']??'') ?>"></label>
<label class="<?= $field('academic_session') ?>">Academic Session<input name="academic_session" value="<?= e($values['academic_session']??'') ?>" placeholder="2025-2026" pattern="\d{4}-\d{4}" required><?php if(isset($errors['academic_session'])):?><b><?= e($errors['academic_session']) ?></b><?php endif;?></label>
<label class="<?= $field('name') ?>">Full Name<input name="name" value="<?= e($values['name']??'') ?>" required><?php if(isset($errors['name'])):?><b><?= e($errors['name']) ?></b><?php endif;?></label>
<label class="<?= $field('mobile_number') ?>">Mobile Number<input name="mobile_number" value="<?= e($values['mobile_number']??'') ?>" inputmode="tel" maxlength="20" required><?php if(isset($errors['mobile_number'])):?><b><?= e($errors['mobile_number']) ?></b><?php endif;?></label>
<label class="<?= $field('address') ?>">Address<textarea name="address" rows="3" required><?= e($values['address']??'') ?></textarea><?php if(isset($errors['address'])):?><b><?= e($errors['address']) ?></b><?php endif;?></label>
</div></section>
<section class="panel form-section"><div class="form-section-heading"><p class="eyebrow">Academic placement</p><h2>School, department and branch</h2></div><div class="form-grid two">
<label>Programme Mapping<select name="programme_id"><option value="">Detect from roll number</option><?php foreach($programmes as $programme):?><option value="<?= (int)$programme['id'] ?>" <?= (int)($values['programme_id']??0)===(int)$programme['id']?'selected':'' ?>><?= e($programme['code'].' - '.$programme['name']) ?></option><?php endforeach;?></select></label>
<label class="<?= $field('branch') ?>">Branch<input name="branch" value="<?= e($values['branch']??'') ?>" required><?php if(isset($errors['branch'])):?><b><?= e($errors['branch']) ?></b><?php endif;?></label>
<label class="<?= $field('department_name') ?>">Department<input name="department_name" value="<?= e($values['department_name']??'') ?>" required><?php if(isset($errors['department_name'])):?><b><?= e($errors['department_name']) ?></b><?php endif;?></label>
<label class="<?= $field('school_name') ?>">School<input name="school_name" value="<?= e($values['school_name']??'') ?>" required><?php if(isset($errors['school_name'])):?><b><?= e($errors['school_name']) ?></b><?php endif;?></label>
<label class="<?= $field('current_year_of_study') ?>">Current Year of Study<select name="current_year_of_study" required><option value="">Select year</option><?php for($year=1;$year<=8;$year++):?><option value="<?= $year ?>" <?= (int)($values['current_year_of_study']??0)===$year?'selected':'' ?>>Year <?= $year ?></option><?php endfor;?></select><?php if(isset($errors['current_year_of_study'])):?><b><?= e($errors['current_year_of_study']) ?></b><?php endif;?></label>
<label class="<?= $field('semester') ?>">Current Semester<select name="semester" required><option value="">Select semester</option><?php for($semester=1;$semester<=12;$semester++):?><option value="<?= $semester ?>" <?= (int)($values['semester']??0)===$semester?'selected':'' ?>>Semester <?= $semester ?></option><?php endfor;?></select><?php if(isset($errors['semester'])):?><b><?= e($errors['semester']) ?></b><?php endif;?></label>
<label class="<?= $field('section') ?>">Section<input name="section" value="<?= e($values['section']??'') ?>" maxlength="20" placeholder="A" required><?php if(isset($errors['section'])):?><b><?= e($errors['section']) ?></b><?php endif;?></label><label>Status<select name="status"><option value="active" <?= ($values['status']??'active')==='active'?'selected':'' ?>>Active</option><option value="inactive" <?= ($values['status']??'')==='inactive'?'selected':'' ?>>Inactive</option><option value="completed" <?= ($values['status']??'')==='completed'?'selected':'' ?>>Completed</option></select></label>
</div></section><div class="form-actions"><a class="text-button" href="<?= e(url('students')) ?>">Cancel</a><button class="primary-button"><?= $editing?'Save changes':'Create student' ?></button></div></form>
