<?php $pageTitle='Automatic date-sheet planning'; ?>
<section class="page-heading"><div><p class="eyebrow">School-wise scheduler</p><h1>Prepare automatic date sheet</h1><p><?= e($cycle['name']) ?> · Validate academic data, calendar and feasibility before creating a draft.</p></div><div class="heading-actions"><a class="secondary-button" href="<?= e(url('exam-cycles/'.$cycle['id'].'/calendar')) ?>"><i class="ti ti-calendar-cog"></i> Calendar</a><a class="secondary-button" href="<?= e(url('date-sheets/'.$cycle['id'])) ?>"><i class="ti ti-arrow-left"></i> Date sheet</a></div></section>
<?php if($error):?><div class="alert error" role="alert"><?= e($error) ?></div><?php endif;?>
<ol class="scheduler-steps" aria-label="Scheduling workflow"><li class="active"><span>1</span>Scope &amp; rules</li><li class="<?= $result?'active':'' ?>"><span>2</span>Validation</li><li><span>3</span>Generate draft</li><li><span>4</span>Review &amp; publish</li></ol>
<div class="scheduler-layout">
  <form id="scheduler-form" class="panel scheduler-form" method="post" action="<?= e(url('date-sheets/'.$cycle['id'].'/automatic/validate')) ?>" data-preview-url="<?= e(url('date-sheets/'.$cycle['id'].'/automatic/preview')) ?>"><?= csrf_field() ?>
    <header><p class="eyebrow">Generation scope</p><h2>Choose school and cohorts</h2><p>Edit the scope or rules at any time. Checks refresh as you change them; save validation to enable draft generation.</p></header>
    <label>School<select id="scheduler-school" name="school_id" required><option value="">Select school</option><?php foreach($schools as $school):?><option value="<?= (int)$school['id'] ?>" <?= (int)($selection['school_id']??0)===(int)$school['id']?'selected':'' ?>><?= e(($school['short_name']?:$school['code']).' — '.$school['name']) ?></option><?php endforeach;?></select></label>
    <fieldset><legend>Programmes / branches</legend><p class="field-help">Only programmes belonging to the selected school are shown.</p><div id="scheduler-programmes" class="choice-grid"><?php foreach($programmes as $programme):?><label data-school="<?= (int)$programme['school_id'] ?>" hidden><input type="checkbox" name="programme_ids[]" value="<?= (int)$programme['id'] ?>" <?= in_array((int)$programme['id'],array_map('intval',$selection['programme_ids']??[]),true)?'checked':'' ?>><span><strong><?= e($programme['code']) ?></strong><?= e($programme['name']) ?></span></label><?php endforeach;?></div></fieldset>
    <fieldset><legend>Semesters</legend><div class="semester-choices"><?php for($semester=1;$semester<=12;$semester++):?><label><input type="checkbox" name="semesters[]" value="<?= $semester ?>" <?= in_array($semester,array_map('intval',$selection['semesters']??[]),true)?'checked':'' ?>><span><?= $semester ?></span></label><?php endfor;?></div></fieldset>
    <div class="rule-grid"><label>Preferred rest gap<input type="number" name="minimum_gap_days" min="0" max="14" value="<?= (int)($selection['minimum_gap_days']??1) ?>" required><small>Free calendar days requested between papers of the same branch. Gaps are kept by priority when capacity allows; all papers are scheduled on consecutive working days when the calendar is full.</small></label><label>Preferred papers per day<select name="maximum_papers_per_day"><?php for($limit=1;$limit<=3;$limit++):?><option value="<?= $limit ?>" <?= (int)($selection['maximum_papers_per_day']??1)===$limit?'selected':'' ?>><?= $limit ?> per cohort</option><?php endfor;?></select><small>The scheduler may use additional configured shifts when this preference cannot fit every paper.</small></label></div>
    <div class="rule-switches"><label><input type="checkbox" name="use_subject_priority" value="1" <?= !array_key_exists('use_subject_priority',$selection)||!empty($selection['use_subject_priority'])?'checked':'' ?>><span><strong>Use subject priority</strong>Give higher-priority subjects the earliest placements and available rest gaps.</span></label><label><input type="checkbox" name="avoid_consecutive_days" value="1" <?= !array_key_exists('avoid_consecutive_days',$selection)||!empty($selection['avoid_consecutive_days'])?'checked':'' ?>><span><strong>Prefer non-consecutive days</strong>Keep a free day when capacity permits; relax this preference rather than leaving a paper unscheduled.</span></label></div>
    <button class="primary-button scheduler-submit"><i class="ti ti-shield-check"></i> Save validation and enable draft</button>
  </form>
  <section class="panel validation-panel" aria-live="polite">
    <div id="live-validation" class="validation-live" hidden></div>
    <div id="saved-validation">
    <?php if(!$result):?><div class="validation-empty"><i class="ti ti-clipboard-check"></i><h2>Validation has not run</h2><p>Select the scope and rules. The application will check curriculum, exam days, shifts, existing papers and available slots without changing the date sheet.</p></div>
    <?php else:?><header class="validation-summary <?= e($result['status']) ?>"><div><p class="eyebrow">Run #<?= (int)$result['run_id'] ?></p><h2><?= $result['blocked']?'Generation blocked':'Ready to generate' ?></h2><p><?= (int)$result['blocked'] ?> blocked · <?= (int)$result['warnings'] ?> warnings</p></div><i class="ti <?= $result['blocked']?'ti-circle-x':'ti-circle-check' ?>"></i></header>
      <?php foreach(['Academic','Calendar','Feasibility'] as $group):?><div class="validation-group"><h3><?= e($group) ?></h3><?php foreach($result['checks'] as $check):if($check['group']!==$group)continue;?><article class="validation-check <?= e($check['state']) ?>"><i class="ti <?= $check['state']==='pass'?'ti-check':($check['state']==='warning'?'ti-alert-triangle':'ti-x') ?>"></i><div><strong><?= e(strtoupper($check['state'])) ?></strong><p><?= e($check['message']) ?></p></div></article><?php endforeach;?></div><?php endforeach;?>
      <?php if(!$result['blocked']):?><form method="post" action="<?= e(url('date-sheets/'.$cycle['id'].'/automatic/generate')) ?>" class="generate-draft-form"><?= csrf_field() ?><input type="hidden" name="run_id" value="<?= (int)$result['run_id'] ?>"><button class="primary-button"><i class="ti ti-wand"></i> Generate deterministic draft</button><p>This creates draft examinations only. Nothing is published.</p></form><?php else:?><button class="primary-button" disabled><i class="ti ti-lock"></i> Resolve blocked checks first</button><?php endif;?><?php endif;?>
    </div>
  </section>
</div>
<script>(()=>{const form=document.getElementById('scheduler-form'),school=document.getElementById('scheduler-school'),items=[...document.querySelectorAll('#scheduler-programmes [data-school]')],live=document.getElementById('live-validation'),saved=document.getElementById('saved-validation');let timer,controller,version=0;const escape=value=>String(value).replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));function sync(clear){items.forEach(item=>{const show=item.dataset.school===school.value;item.hidden=!show;if(clear&&!show)item.querySelector('input').checked=false;});}function render(result){const groups=['Academic','Calendar','Feasibility'];live.innerHTML='<header class="validation-summary '+escape(result.status)+'"><div><p class="eyebrow">Live preview · unsaved</p><h2>'+(result.blocked?'Changes needed':'Ready to save validation')+'</h2><p>'+result.blocked+' blocked · '+result.warnings+' warnings</p></div></header>'+groups.map(group=>'<div class="validation-group"><h3>'+group+'</h3>'+result.checks.filter(check=>check.group===group).map(check=>'<article class="validation-check '+escape(check.state)+'"><i class="ti '+(check.state==='pass'?'ti-check':check.state==='warning'?'ti-alert-triangle':'ti-x')+'"></i><div><strong>'+escape(check.state.toUpperCase())+'</strong><p>'+escape(check.message)+'</p></div></article>').join('')+'</div>').join('')+'<p class="validation-live-note">This preview does not create a run. Save validation after editing to generate a draft.</p>';}
function update(){clearTimeout(timer);if(controller)controller.abort();version++;saved.hidden=true;live.hidden=false;if(!school.value||!form.querySelector('input[name="programme_ids[]"]:checked')||!form.querySelector('input[name="semesters[]"]:checked')){live.innerHTML='<div class="validation-empty"><h2>Choose a school, programme and semester</h2><p>Checks will update as you edit the form.</p></div>';return;}const current=version;live.innerHTML='<div class="validation-empty"><h2>Checking changes…</h2></div>';timer=setTimeout(async()=>{controller=new AbortController();try{const response=await fetch(form.dataset.previewUrl,{method:'POST',body:new FormData(form),credentials:'same-origin',signal:controller.signal,headers:{'Accept':'application/json'}});const data=await response.json();if(current!==version)return;if(!response.ok)throw new Error(data.error||'Validation could not be completed.');render(data);}catch(error){if(error.name!=='AbortError'&&current===version)live.innerHTML='<div class="validation-empty"><h2>Validation unavailable</h2><p>'+escape(error.message)+'</p></div>'; }},350);}school.addEventListener('change',()=>{sync(true);update();});form.addEventListener('change',event=>{if(event.target!==school)update();});form.addEventListener('input',event=>{if(event.target.name==='minimum_gap_days')update();});sync(false);})();</script>
