<?php $pageTitle='Calendar & holidays';$enabled=count(array_filter($dates,static fn($date)=>(int)$date['is_exam_day']===1)); ?>
<section class="page-heading calendar-heading"><div><p class="eyebrow">Automatic scheduling foundation</p><h1>Calendar &amp; holidays</h1><p><?= e($cycle['name']) ?> · <?= e(date('d M Y',strtotime($cycle['start_date']))) ?>–<?= e(date('d M Y',strtotime($cycle['end_date']))) ?></p></div><div class="heading-actions"><a class="secondary-button" href="<?= e(url('date-sheets/'.$cycle['id'])) ?>"><i class="ti ti-arrow-left"></i> Date sheet</a></div></section>
<?php if($success):?><div class="alert success" role="status"><?= e($success) ?></div><?php endif;?><?php if($error):?><div class="alert error" role="alert"><?= e($error) ?></div><?php endif;?>
<section class="calendar-summary"><div><i class="ti ti-calendar-check"></i><span>Enabled exam days<strong><?= $enabled ?></strong></span></div><div><i class="ti ti-calendar-off"></i><span>Excluded dates<strong><?= count($dates)-$enabled ?></strong></span></div><p><i class="ti ti-info-circle"></i> Automatic scheduling will never place a paper on an excluded date. Sundays are excluded by default.</p></section>
<form method="post" action="<?= e(url('exam-cycles/'.$cycle['id'].'/calendar')) ?>" class="panel calendar-register"><?= csrf_field() ?>
  <div class="calendar-toolbar"><div><p class="eyebrow">Cycle calendar</p><h2>Confirm working and non-working dates</h2></div><button class="primary-button"><i class="ti ti-device-floppy"></i> Save calendar</button></div>
  <div class="table-scroll"><table><thead><tr><th>Date</th><th>Day</th><th>Classification</th><th>Available for exams</th><th>Administrative note</th></tr></thead><tbody>
  <?php foreach($dates as $date):$weekend=date('N',strtotime($date['exam_date']))==='7';?><tr class="<?= (int)$date['is_exam_day']===0?'calendar-row-off':'' ?>"><td><strong><?= e(date('d M Y',strtotime($date['exam_date']))) ?></strong></td><td><?= e(date('l',strtotime($date['exam_date']))) ?></td><td><select name="dates[<?= (int)$date['id'] ?>][day_type]" class="day-type"><option value="exam_day" <?= $date['day_type']==='exam_day'?'selected':'' ?>>Exam day</option><option value="sunday" <?= $date['day_type']==='sunday'?'selected':'' ?>>Sunday</option><option value="holiday" <?= $date['day_type']==='holiday'?'selected':'' ?>>University holiday</option><option value="restricted_holiday" <?= $date['day_type']==='restricted_holiday'?'selected':'' ?>>Restricted holiday</option><option value="preparation_day" <?= $date['day_type']==='preparation_day'?'selected':'' ?>>Preparation day</option><option value="blocked" <?= $date['day_type']==='blocked'?'selected':'' ?>>Blocked</option></select></td><td><label class="calendar-toggle"><input type="checkbox" name="dates[<?= (int)$date['id'] ?>][is_exam_day]" value="1" <?= (int)$date['is_exam_day']===1?'checked':'' ?>><span>Use date</span></label></td><td><input name="dates[<?= (int)$date['id'] ?>][note]" value="<?= e((string)$date['note']) ?>" placeholder="Holiday name or reason"></td></tr><?php endforeach;?>
  </tbody></table></div>
</form>
<script>(()=>{document.querySelectorAll('.day-type').forEach(select=>select.addEventListener('change',()=>{const row=select.closest('tr'),box=row.querySelector('input[type=checkbox]');if(select.value!=='exam_day')box.checked=false;row.classList.toggle('calendar-row-off',!box.checked);}));document.querySelectorAll('.calendar-toggle input').forEach(box=>box.addEventListener('change',()=>box.closest('tr').classList.toggle('calendar-row-off',!box.checked)));})();</script>
