<?php $pageTitle='Create exam cycle';$error=app()->session()->pullFlash('error');$old=app()->session()->pullFlash('cycle_old',[]);$value=static fn(string $key,string $default=''): string=>e((string)($old[$key]??$default)); ?>
<div class="cycle-create-page">
  <section class="cycle-create-heading"><div class="cycle-create-brand"><img src="<?= e(url('assets/images/gbu-emblem.png')) ?>" alt="" width="48" height="48"><div><span>Gautam Buddha University</span><strong>Examination planning</strong></div></div><h1>Create examination cycle</h1><p>Define the academic period and working sessions. The system creates the calendar and shift structure automatically.</p><a href="<?= e(url('exam-cycles')) ?>">← Back to cycle register</a></section>
  <?php if($error):?><div class="alert error" role="alert"><?= e($error) ?></div><?php endif;?>
  <form id="cycle-builder" class="cycle-builder" method="post" action="<?= e(url('exam-cycles')) ?>"><?= csrf_field() ?>
    <div class="cycle-builder-main">
      <section class="cycle-form-block" aria-labelledby="period-title"><header><span>Academic period</span><h2 id="period-title">Cycle details</h2><p>Name the examination and define the inclusive calendar range.</p></header><div class="cycle-fields two">
        <label class="wide">Cycle name<input id="cycle-name" name="name" value="<?= $value('name') ?>" placeholder="Mid-Semester Examination March 2026" required></label>
        <label>Academic year<input id="academic-year" name="academic_year" value="<?= $value('academic_year','2025-26') ?>" placeholder="2025-26" required></label>
        <label>Examination type<select id="exam-type" name="exam_type"><option value="mid_sem" <?= ($old['exam_type']??'mid_sem')==='mid_sem'?'selected':'' ?>>Mid-Semester</option><option value="end_sem" <?= ($old['exam_type']??'')==='end_sem'?'selected':'' ?>>End-Semester</option><option value="repeat" <?= ($old['exam_type']??'')==='repeat'?'selected':'' ?>>Repeat Paper</option><option value="back_paper" <?= ($old['exam_type']??'')==='back_paper'?'selected':'' ?>>Back Paper</option><option value="special_back_paper" <?= ($old['exam_type']??'')==='special_back_paper'?'selected':'' ?>>Special Back Paper</option><option value="pass_out_special" <?= ($old['exam_type']??'')==='pass_out_special'?'selected':'' ?>>Pass-Out Special</option><option value="not_promoted_special" <?= ($old['exam_type']??'')==='not_promoted_special'?'selected':'' ?>>Not-Promoted Special</option></select></label>
        <label>Paper duration<input id="duration" type="number" name="duration" value="<?= $value('duration','90') ?>" min="30" max="300" step="5" required><small>30 to 300 minutes</small></label>
        <label>Start date<input id="start-date" type="date" name="start_date" value="<?= $value('start_date') ?>" required></label><label>End date<input id="end-date" type="date" name="end_date" value="<?= $value('end_date') ?>" required></label>
      </div></section>
      <section class="cycle-form-block" aria-labelledby="shift-title"><header><span>Session structure</span><h2 id="shift-title">Examination shifts</h2><p>Configure two non-overlapping sessions. Timings remain editable for every cycle.</p></header><div class="shift-editor">
        <fieldset><legend>First shift</legend><label>Shift name<input id="shift1-name" name="shift1_name" value="<?= $value('shift1_name','Morning Shift') ?>" required></label><div><label>Starts<input id="shift1-start" type="time" name="shift1_start" value="<?= $value('shift1_start','10:00') ?>" required></label><label>Ends<input id="shift1-end" type="time" name="shift1_end" value="<?= $value('shift1_end','11:30') ?>" required></label></div></fieldset>
        <fieldset><legend>Second shift</legend><label>Shift name<input id="shift2-name" name="shift2_name" value="<?= $value('shift2_name','Evening Shift') ?>" required></label><div><label>Starts<input id="shift2-start" type="time" name="shift2_start" value="<?= $value('shift2_start','15:00') ?>" required></label><label>Ends<input id="shift2-end" type="time" name="shift2_end" value="<?= $value('shift2_end','16:30') ?>" required></label></div></fieldset>
      </div></section>
    </div>
    <aside class="cycle-summary"><div class="cycle-summary-logo"><img src="<?= e(url('assets/images/gbu-emblem.png')) ?>" alt="" width="48" height="48"><span>Cycle summary</span></div><h2 id="summary-name">New examination cycle</h2><dl><div><dt>Academic year</dt><dd id="summary-year">2025-26</dd></div><div><dt>Type</dt><dd id="summary-type">Mid-Semester</dd></div><div><dt>Date range</dt><dd id="summary-dates">Select dates</dd></div><div><dt>Duration</dt><dd id="summary-duration">90 minutes</dd></div><div><dt>Sessions</dt><dd id="summary-shifts">2 configured shifts</dd></div></dl><p>The cycle opens as a draft. Papers and student eligibility are added from its date sheet.</p><button class="cycle-create-button" type="submit"><span>Create calendar</span><b aria-hidden="true">→</b></button><a href="<?= e(url('exam-cycles')) ?>">Cancel and return</a></aside>
  </form>
</div>
<script>(()=>{const form=document.getElementById('cycle-builder'),get=id=>document.getElementById(id),set=(id,text)=>get(id).textContent=text,types=get('exam-type');const update=()=>{set('summary-name',get('cycle-name').value.trim()||'New examination cycle');set('summary-year',get('academic-year').value.trim()||'Not entered');set('summary-type',types.options[types.selectedIndex].text);const start=get('start-date').value,end=get('end-date').value;set('summary-dates',start&&end?`${start} to ${end}`:'Select dates');set('summary-duration',`${get('duration').value||0} minutes`);const names=[get('shift1-name').value,get('shift2-name').value].filter(Boolean);set('summary-shifts',names.length===2?names.join(' and '):`${names.length} configured shifts`);};form.querySelectorAll('input,select').forEach(field=>field.addEventListener('input',update));types.addEventListener('change',()=>{if(!get('duration').dataset.changed)get('duration').value=types.value==='mid_sem'?'90':'180';update();});get('duration').addEventListener('input',()=>get('duration').dataset.changed='1');get('end-date').addEventListener('change',()=>get('end-date').setCustomValidity(get('start-date').value&&get('end-date').value<get('start-date').value?'End date must be after the start date.':''));form.querySelectorAll('input[type=time]').forEach(field=>field.addEventListener('change',()=>{const prefix=field.id.startsWith('shift1')?'shift1':'shift2',start=get(prefix+'-start'),end=get(prefix+'-end');end.setCustomValidity(start.value&&end.value<=start.value?'Shift end must be after its start time.':'');}));update();})();</script>
