<?php $pageTitle='Exam cycles';$totals=['all'=>count($cycles),'draft'=>0,'published'=>0,'closed'=>0,'archived'=>0];foreach($cycles as $item)if(isset($totals[$item['status']]))$totals[$item['status']]++; ?>
<div class="cycles-page">
  <section class="cycles-hero" aria-labelledby="cycles-title">
    <div class="cycles-hero-main"><div class="cycles-brand"><img src="<?= e(url('assets/images/gbu-emblem.png')) ?>" alt="" width="50" height="50"><div><strong>Gautam Buddha University</strong><span>Examination Cell</span></div></div><h1 id="cycles-title">Examination cycles</h1><p>Plan calendars, configure shifts, schedule papers, and manage seating versions from one governed workspace.</p></div>
    <div class="cycles-hero-side"><span>Planning workspace</span><strong><?= number_format($totals['all']) ?> cycles recorded</strong><a href="<?= e(url('exam-cycles/create')) ?>">Create examination cycle <b aria-hidden="true">→</b></a></div>
  </section>
  <?php if($success):?><div class="alert success" role="status"><?= e($success) ?></div><?php endif;?><?php if($error):?><div class="alert error" role="alert"><?= e($error) ?></div><?php endif;?>
  <section class="cycles-toolbar" aria-label="Cycle filters"><div><strong>Cycle register</strong><span>Filter by current publication status.</span></div><div class="cycle-filters"><button type="button" class="active" data-cycle-filter="all">All <span><?= $totals['all'] ?></span></button><button type="button" data-cycle-filter="draft">Draft <span><?= $totals['draft'] ?></span></button><button type="button" data-cycle-filter="published">Published <span><?= $totals['published'] ?></span></button><button type="button" data-cycle-filter="closed">Closed <span><?= $totals['closed'] ?></span></button></div></section>
  <?php if($cycles):?><section class="cycle-register" aria-live="polite">
    <?php foreach($cycles as $cycle):$days=max(1,(int)((strtotime($cycle['end_date'])-strtotime($cycle['start_date']))/86400)+1);?>
      <article class="cycle-record" data-cycle-status="<?= e($cycle['status']) ?>">
        <div class="cycle-record-identity"><div class="cycle-status-line"><span class="status-label <?= e($cycle['status']) ?>"><?= e(ucfirst($cycle['status'])) ?></span><span><?= e($cycle['academic_year']) ?></span></div><h2><?= e($cycle['name']) ?></h2><p><?= e(date('d M Y',strtotime($cycle['start_date']))) ?> to <?= e(date('d M Y',strtotime($cycle['end_date']))) ?> <span><?= $days ?> calendar days</span></p></div>
        <dl class="cycle-record-metrics"><div><dt>Papers</dt><dd><?= number_format((int)$cycle['paper_count']) ?></dd></div><div><dt>Eligible</dt><dd><?= number_format((int)$cycle['eligible_count']) ?></dd></div><div><dt>Shifts</dt><dd><?= number_format((int)$cycle['shift_count']) ?></dd></div><div><dt>Seating versions</dt><dd><?= number_format((int)$cycle['allocation_count']) ?></dd></div></dl>
        <div class="cycle-record-action"><span><?= e(ucwords(str_replace('_',' ',$cycle['exam_type']))) ?></span><small><?= (int)$cycle['default_duration_minutes'] ?> minutes per paper</small><a href="<?= e(url('date-sheets/'.$cycle['id'])) ?>">Open date sheet <b aria-hidden="true">→</b></a></div>
      </article>
    <?php endforeach;?>
    <div class="cycle-filter-empty" hidden><strong>No cycles in this status</strong><span>Choose another filter to continue.</span></div>
  </section><?php else:?><section class="cycles-empty"><img src="<?= e(url('assets/images/gbu-emblem.png')) ?>" alt="" width="72" height="72"><h2>No examination cycles yet</h2><p>Create a cycle to configure dates, shifts, papers, eligibility, and seating.</p><a href="<?= e(url('exam-cycles/create')) ?>">Create the first cycle</a></section><?php endif;?>
</div>
<script>(()=>{const buttons=[...document.querySelectorAll('[data-cycle-filter]')],records=[...document.querySelectorAll('[data-cycle-status]')],empty=document.querySelector('.cycle-filter-empty');buttons.forEach(button=>button.addEventListener('click',()=>{buttons.forEach(item=>item.classList.toggle('active',item===button));const filter=button.dataset.cycleFilter;let visible=0;records.forEach(record=>{const show=filter==='all'||record.dataset.cycleStatus===filter;record.hidden=!show;if(show)visible++;});if(empty)empty.hidden=visible!==0;}));})();</script>
