<?php $pageTitle='Schedule paper'; ?>
<section class="page-heading"><div><p class="eyebrow"><?= e($cycle['name']) ?></p><h1>Schedule examination paper</h1><p>Choose the batch and semester first. Only subjects assigned to that exact batch curriculum are available.</p></div><a class="secondary-button" href="<?= e(url('date-sheets/'.$cycle['id'])) ?>">Back to date sheet</a></section>
<?php if($error):?><div class="alert error"><?= e($error) ?></div><?php endif;?>
<form class="record-form" method="post" action="<?= e(url('date-sheets/'.$cycle['id'].'/papers')) ?>"><?= csrf_field() ?><section class="panel form-section"><div class="form-section-heading"><p class="eyebrow">Paper</p><h2>Course and cohort</h2></div><div class="form-grid two">
<label>Programme / branch<select name="programme_id" id="schedule-programme" required><option value="">Select programme first</option><?php foreach($programmes as $programme):?><option value="<?= (int)$programme['id'] ?>"><?= e($programme['code'].' - '.$programme['name']) ?></option><?php endforeach;?></select></label>
<label>Academic batch<select name="batch_label" id="schedule-batch" required disabled><option value="">Select programme first</option><?php foreach($batches as $batch):?><option value="<?= e($batch['label']) ?>" data-id="<?= (int)$batch['id'] ?>" data-programme="<?= (int)$batch['programme_id'] ?>"><?= e($batch['label']) ?></option><?php endforeach;?></select></label>
<label>Semester<select name="semester" id="schedule-semester" required><option value="">Select semester</option><?php for($i=1;$i<=12;$i++):?><option value="<?= $i ?>">Semester <?= $i ?></option><?php endfor;?></select></label><label>Section<select name="section" id="schedule-section" required disabled><option value="">Choose batch and semester</option></select></label>
<label>Subject / course<select name="course_id" id="schedule-course" required disabled><option value="">Choose batch, semester and section</option><?php foreach($courses as $course):?><option value="<?= (int)$course['id'] ?>" data-programme="<?= (int)$course['programme_id'] ?>" data-batch="<?= (int)($course['batch_id']??0) ?>" data-semester="<?= (int)$course['semester'] ?>" data-section="<?= e($course['section']) ?>"><?= e($course['code'].' - '.$course['name']) ?></option><?php endforeach;?></select><small id="course-guidance">Subjects are loaded from the selected batch and section curriculum.</small></label>
<label>Display label<input name="display_label" placeholder="UCS 2023-2027, Semester 1"></label><label>Examination date<select name="exam_date" required><?php foreach($dates as $date):?><option value="<?= e($date) ?>"><?= e(date('l, d F Y',strtotime($date))) ?></option><?php endforeach;?></select></label><label>Shift<select name="shift_id" required><?php foreach($shifts as $shift):?><option value="<?= (int)$shift['id'] ?>"><?= e($shift['name'].' '.substr($shift['start_time'],0,5).'-'.substr($shift['end_time'],0,5)) ?></option><?php endforeach;?></select></label><label>Category<select name="category"><option value="regular">Regular</option><option value="repeat">Repeat</option><option value="back_paper">Back Paper</option><option value="special">Special</option><option value="pass_out">Pass-Out</option><option value="not_promoted">Not-Promoted</option></select></label>
</div></section><div class="form-actions"><a class="text-button" href="<?= e(url('date-sheets/'.$cycle['id'])) ?>">Cancel</a><button class="primary-button">Schedule and calculate eligibility</button></div></form>
<script>(()=>{const programme=document.getElementById('schedule-programme'),batch=document.getElementById('schedule-batch'),semester=document.getElementById('schedule-semester'),section=document.getElementById('schedule-section'),course=document.getElementById('schedule-course'),guidance=document.getElementById('course-guidance'),batchSource=[...batch.options].slice(1).map(o=>o.cloneNode(true)),courseSource=[...course.options].slice(1).map(o=>o.cloneNode(true));function baseMatches(){const b=batch.selectedOptions[0]?.dataset.id||'';return courseSource.filter(o=>o.dataset.programme===programme.value&&o.dataset.semester===semester.value&&(o.dataset.batch===b||o.dataset.batch==='0'));}function syncBatches(){const old=batch.value;batch.innerHTML='<option value="">Select academic batch</option>';batchSource.filter(o=>o.dataset.programme===programme.value).forEach(o=>batch.append(o.cloneNode(true)));batch.disabled=!programme.value||batch.options.length===1;if([...batch.options].some(o=>o.value===old))batch.value=old;syncSections();}function syncSections(){const old=section.value,values=[...new Set(baseMatches().map(o=>o.dataset.section))];section.innerHTML='<option value="">Select section</option>'+values.map(v=>`<option value="${v}">${v==='ALL'?'All sections':`Section ${v}`}</option>`).join('');section.disabled=values.length===0;if(values.includes(old))section.value=old;else if(values.length===1)section.value=values[0];syncCourses();}function syncCourses(){const matches=baseMatches().filter(o=>o.dataset.section===section.value);course.innerHTML='<option value="">Select curriculum subject</option>';matches.forEach(o=>course.append(o.cloneNode(true)));course.disabled=!section.value||matches.length===0;guidance.textContent=!programme.value||!batch.value||!semester.value?'Choose a programme, batch and semester first.':!section.value?'Choose a section.':matches.length?`${matches.length} subject${matches.length===1?'':'s'} in this batch and section.`:'No subject is mapped here.';}programme.addEventListener('change',syncBatches);batch.addEventListener('change',syncSections);semester.addEventListener('change',syncSections);section.addEventListener('change',syncCourses);syncBatches();})();</script>
